### PR TITLE
Add umd pattern

### PR DESCRIPTION
**Pull request by drazik**
Hello,

Here is a proposition to add UMD to the plugin. This way it can be used with AMD, CommonJS or globals.

I used [umdjs/umd returnExports pattern](https://github.com/umdjs/umd/blob/master/templates/returnExports.js).

I also included a .gitignore file to ignore node_modules and npm-debug.log. If your don't want this I can delete it.

(This is my very first PR to a repository that is not mine on github. I hope I did it the right way)

Edit : oops, I've just become aware of the possibility to have a global gitignore. Maybe that's why you have no .gitignore in the repository and I made a mistake by adding one ?

### CODE REVIEW

**Comment by eduardoboucas** [comment]
My only problem with this is that it breaks the current API, right? How would someone go about using the library without AMD or CommonJS?

**Comment by drazik** [comment]
Actually no, because `root` willl receive `this`, which is the global object (`window` in the browser) when you import the file with a `<script>` tag.

I did a little test, I have an index.html file : 

``` html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
    </head>
    <body>
        <script src="../dist/include-media-1.0.1.min.js"></script>
    </body>
</html>
```

And when I type `window.im` in the console, here is the result : 

```
im
Object { setElement: e(), setUpdateMode: t(), greaterThan: a(), lessThan: o(), getActive: r(), getValue: u(), update: n() }
```

It means the current API is not broken at all :)

**Comment by drazik** [comment]
Did you find some time to review it @eduardoboucas ?

**Comment by eduardoboucas** [comment]
Thanks!

**Pull request merged**
